# Generated by Django 5.1.2 on 2024-10-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
