# Generated by Django 5.1.2 on 2024-11-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_add_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
