# Generated by Django 5.1.2 on 2024-11-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0006_alter_account_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
