# Generated by Django 5.1.2 on 2024-10-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0010_alter_employee_managers_remove_employee_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
    ]
