# Generated by Django 5.1.2 on 2024-10-27 04:45

from django.db import migrations
from django.contrib.auth.models import Group

def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name="Employee")
    Group.objects.get_or_create(name="Administrator")

class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0012_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
