# Generated by Django 5.1.2 on 2024-10-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usermgmt', '0013_auto_20241027_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
