# Generated by Django 5.1.2 on 2024-10-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0016_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
    ]
