"""
Django settings for AMSystem project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# ===================
# BASE CONFIGURATION
# ===================
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=creds)y8n8cm*s^#94miq+mz!*ico7he37&gb5o0u%pa-53e-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ===================
# APPLICATIONS
# ===================
INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'attendance',
    'dashboard',
    'userauth',
    'usermgmt',
    'django_browser_reload',
]


# ===================
# MIDDLEWARE
# ===================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ===================
# URL CONFIGURATION
# ===================
ROOT_URLCONF = 'AMSystem.urls'


# ===================
# TEMPLATES
# ===================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Ensure this points to your templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ===================
# WSGI APPLICATION
# ===================
WSGI_APPLICATION = 'AMSystem.wsgi.application'


# ===================
# DATABASES
# ===================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ===================
# AUTHENTICATION
# ===================
AUTH_USER_MODEL = 'usermgmt.User'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # This is the default
)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===================
# INTERNATIONALIZATION
# ===================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ===================
# STATIC FILES
# ===================
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# ===================
# DEFAULT PRIMARY KEY FIELD TYPE
# ===================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===================
# TAILWIND SETTINGS
# ===================
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = 'C:/Program Files/nodejs/npm.cmd'


# ===================
# INTERNALS
# ===================
INTERNAL_IPS = [
    "127.0.0.1",
]

LOGIN_URL = 'login'


# ===================
# SESSION SETTINGS
# ===================
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1  # Set a custom session expiry (in seconds) for testing