# Generated by Django 5.1.2 on 2024-12-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
